"""Add rating fields

Revision ID: 05c149e955da
Revises: 2d89b4228948
Create Date: 2021-01-02 23:55:31.170976

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '05c149e955da'
down_revision = '2d89b4228948'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'links',
        sa.Column('rating', sa.SmallInteger(), nullable=True, default=0)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'rating')
    # ### end Alembic commands ###
